Repository shchegol/reactive-battle, pull requests merged in 2020-12, with the labels that each got.

#10 #9 Создать с помощью React-стека все страницы кроме игры. (регистрация / авторизация)
  .eslintrc.json
  package-lock.json
  package.json
  src/components/app/App.tsx
  src/components/logo/Logo.tsx
  src/components/logo/index.ts
  src/components/title/Title.tsx
  src/components/title/index.ts
  src/index.tsx
  src/pages/signin/Signin.tsx
  src/pages/signin/signin.scss
  src/pages/signup/Signup.tsx
  src/pages/signup/signup.scss
  src/styles/common/_base.scss
  src/styles/utilities/_variables.scss
  src/svg/logo.svg
  svgTransform.js
  webpack/webpack.common.js
Labels: API

#13 #9 pages
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  src/components/app/App.tsx
  src/components/logo/Logo.tsx
  src/components/logo/index.ts
  src/components/title/Title.tsx
  src/components/title/index.ts
  src/index.tsx
  src/pages/signin/Signin.tsx
  src/pages/signin/signin.scss
  src/pages/signup/Signup.tsx
  src/pages/signup/signup.scss
  src/styles/common/_base.scss
  src/styles/utilities/_variables.scss
  src/svg/logo.svg
  svgTransform.js
  webpack/webpack.common.js
Labels: спринт1

#16 #12 npm build fix
  .eslintrc.json
  package-lock.json
  package.json
  webpack/webpack.common.js
Labels: invalid, спринт1

#15 #7 router
  src/components/app/App.tsx
  src/components/logo/Logo.tsx
  src/images/logo.svg
  src/pages/signup/Signup.tsx
  webpack/webpack.dev.js
Labels: спринт1

#20 #8 auth api
  .eslintrc.json
  package-lock.json
  package.json
  src/api/AuthAPI.ts
  src/components/app/App.tsx
  src/components/loginForm/LoginForm.tsx
  src/components/privateRoute/PrivateRoute.tsx
  src/components/privateRoute/index.ts
  src/components/registrationForm/RegistrationForm.tsx
  src/constants.ts
  src/context/auth.tsx
  src/pages/signin/SignIn.tsx
  src/pages/signin/Signin.tsx
  src/pages/signup/SignUp.tsx
  src/pages/signup/Signup.tsx
  src/styles/common/_base.scss
  src/utils/objectUtils.ts
  src/utils/stringUtils.ts
  tsconfig.json
Labels: API, спринт1

#19 #6 game
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  src/components/app/App.tsx
  src/components/button/Button.tsx
  src/components/button/button.scss
  src/components/button/index.ts
  src/components/button/types.ts
  src/components/leadersItem/LeadersItem.tsx
  src/components/leadersItem/index.ts
  src/components/leadersItem/leadersItem.scss
  src/components/leadersItem/types.ts
  src/components/leadersTable/LeadersTable.tsx
  src/components/leadersTable/index.ts
  src/components/leadersTable/leadersTable.scss
  src/components/leadersTable/types.ts
  src/components/loginForm/LoginForm.tsx
  src/components/logo/Logo.tsx
  src/components/playground/Playground.tsx
  src/components/playground/index.ts
  src/components/privateRoute/PrivateRoute.tsx
  src/components/registrationForm/RegistrationForm.tsx
  src/components/searchBox/SearchBox.tsx
  src/components/searchBox/index.ts
  src/components/searchBox/searchBox.scss
  src/components/searchBox/types.ts
  src/components/subtitle/Subtitle.tsx
  src/components/subtitle/index.ts
  src/components/subtitle/subtitle.scss
  src/components/subtitle/types.ts
  src/images/bang.png
  src/images/wrong-way.jpg
  src/pages/error404/Error404.tsx
  src/pages/error404/error404.scss
  src/pages/error404/index.ts
  src/pages/error5xx/Error5xx.tsx
  src/pages/error5xx/error5xx.scss
  src/pages/error5xx/index.ts
  src/pages/error5xx/types.ts
  src/pages/game/Game.tsx
  src/pages/game/game.scss
  src/pages/leaderboard/Leaderboard.tsx
  src/pages/leaderboard/leaderboard.scss
  src/pages/signin/SignIn.tsx
  src/pages/signup/SignUp.tsx
  src/store/types.ts
  src/styles/common/_base.scss
  src/styles/utilities/_variables.scss
  src/utils/stringUtils.ts
Labels: спринт1

#24 error boundary
  src/components/app/App.tsx
  src/components/errorBoundary/ErrorBoundary.tsx
  src/components/errorBoundary/index.ts
  src/components/errorBoundary/types.ts
  src/utils/objectUtils.ts
Labels: enhancement, спринт1

#22 input-to-component /
  src/components/input/Input.tsx
  src/components/input/index.ts
  src/components/input/input.scss
  src/components/input/types.ts
  src/components/loginForm/LoginForm.tsx
  src/components/registrationForm/RegistrationForm.tsx
  src/components/searchBox/SearchBox.tsx
  src/components/searchBox/searchBox.scss
  src/index.html
  src/styles/common/_base.scss
  src/styles/utilities/_variables.scss
  src/utils/toClassNames.ts
  webpack/webpack.common.js
Labels: bug, спринт1

#23 #6 game
  .vscode/launch.json
  src/components/playground/Playground.tsx
  src/engine/KeyboardManager.ts
  src/engine/Player.ts
  src/engine/Scene.ts
  src/engine/Sprite.ts
  src/engine/SpritesManager.ts
  src/engine/Stage.ts
  src/engine/world/BrickWall.ts
  src/engine/world/ConcreteWall.ts
  src/engine/world/Ice.ts
  src/engine/world/Tree.ts
  src/engine/world/Wall.ts
Labels: engine, спринт1
