Repository shchegol/reactive-battle, pull requests merged in 2021-01, with the labels that each got.

#28 #27 общий рефакторинг /
  src/components/app/App.tsx
  src/components/button/Button.tsx
  src/components/button/button.scss
  src/components/button/types.ts
  src/components/errorBoundary/ErrorBoundary.tsx
  src/components/errorBoundary/types.ts
  src/components/input/Input.tsx
  src/components/leadersItem/LeadersItem.tsx
  src/components/leadersItem/leadersItem.scss
  src/components/leadersItem/types.ts
  src/components/leadersTable/LeadersTable.tsx
  src/components/leadersTable/leadersTable.scss
  src/components/leadersTable/types.ts
  src/components/loginForm/LoginForm.scss
  src/components/loginForm/LoginForm.tsx
  src/components/logo/Logo.tsx
  src/components/logo/index.ts
  src/components/mainTitle/MainTitle.tsx
  src/components/mainTitle/index.ts
  src/components/mainTitle/mainTitle.scss
  src/components/mainTitle/types.ts
  src/components/registrationForm/RegistrationForm.scss
  src/components/registrationForm/RegistrationForm.tsx
  src/components/searchBox/SearchBox.tsx
  src/components/subtitle/Subtitle.tsx
  src/components/subtitle/index.ts
  src/components/subtitle/subtitle.scss
  src/components/subtitle/types.ts
  src/components/title/Title.tsx
  src/components/title/index.ts
  src/engine/SpritesManager.ts
  src/images/tank.png
  src/index.tsx
  src/pages/leaderboard/Leaderboard.tsx
  src/pages/leaderboard/leaderboard.scss
  src/pages/signin/SignIn.tsx
  src/pages/signin/signin.scss
  src/pages/signup/SignUp.tsx
  src/store/types.ts
  src/styles/common/_base.scss
  src/styles/common/_grid.scss
  src/styles/common/_modificators.scss
  src/styles/index.scss
  src/styles/utilities/_flex.scss
  src/styles/utilities/_spacing.scss
  src/styles/utilities/_variables.scss
  src/styles/utilities/mixins/_breakpoints.scss
  src/styles/utilities/mixins/_grid-framework.scss
  src/styles/utilities/mixins/_grid.scss
  webpack/webpack.common.js
Labels: enhancement, спринт1

#30 #25 Страница профиля
  src/api/AuthAPI.ts
  src/components/app/App.tsx
  src/components/button/Button.tsx
  src/components/button/button.scss
  src/pages/game/Game.tsx
  src/pages/game/game.scss
  src/pages/profile/Profile.tsx
  src/styles/common/_modificators.scss
Labels: спринт1

#34 #33 bugfix
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/app/App.tsx
  src/engine/world/Ice.ts
  src/engine/world/Tree.ts
  src/engine/world/Wall.ts
  src/pages/error5xx/Error5xx.tsx
  webpack/webpack.common.js
Labels: bug, спринт1

#36 #26 Форум
  src/components/app/App.tsx
  src/components/button/Button.tsx
  src/components/button/button.scss
  src/components/button/types.ts
  src/components/loginForm/LoginForm.tsx
  src/components/mainTitle/MainTitle.tsx
  src/components/messageItem/MessageItem.tsx
  src/components/messageItem/index.ts
  src/components/messageItem/messageItem.scss
  src/components/messageItem/types.ts
  src/components/messages/Messages.tsx
  src/components/messages/index.ts
  src/components/messages/types.ts
  src/components/newThread/NewThread.tsx
  src/components/newThread/index.ts
  src/components/newThread/types.ts
  src/components/registrationForm/RegistrationForm.tsx
  src/components/replyThread/ReplyThread.tsx
  src/components/replyThread/index.ts
  src/components/replyThread/types.ts
  src/components/searchBox/SearchBox.tsx
  src/components/threadItem/ThreadItem.tsx
  src/components/threadItem/index.ts
  src/components/threadItem/threadItem.scss
  src/components/threadItem/types.ts
  src/components/threads/Threads.tsx
  src/components/threads/index.ts
  src/components/threads/types.ts
  src/pages/forum/Forum.tsx
  src/pages/forumThread/ForumThread.tsx
  src/pages/game/Game.tsx
  src/pages/leaderboard/Leaderboard.tsx
  src/pages/profile/Profile.tsx
  src/store/types.ts
  src/styles/common/_modificators.scss
  src/styles/common/_typography.scss
  src/styles/index.scss
  src/styles/utilities/_variables.scss
Labels: спринт1

#57 #49 redux
  .eslintrc.json
  package-lock.json
  package.json
  src/api/AuthAPI.ts
  src/components/app/App.tsx
  src/components/app/app.spec.tsx
  src/components/privateRoute/PrivateRoute.tsx
  src/components/registrationForm/RegistrationForm.tsx
  src/context/auth.tsx
  src/index.tsx
  src/pages/forum/Forum.tsx
  src/pages/forumThread/ForumThread.tsx
  src/pages/forumThread/types.ts
  src/pages/game/Game.tsx
  src/pages/profile/Profile.tsx
  src/pages/profileEdit/ProfileEdit.tsx
  src/pages/signin/SignIn.tsx
  src/pages/signup/SignUp.tsx
  src/store/actions/auth.ts
  src/store/actionsCreators/auth.ts
  src/store/reducers/auth.ts
  src/store/reducers/forum.ts
  src/store/reducers/index.ts
  src/store/reducers/profile.ts
  src/store/store.ts
  src/store/types.ts
  src/types/models.ts
  src/utils/deepCopy.ts
  src/utils/history.ts
  src/utils/responseHandle.ts
  tsconfig.json
  webpack/webpack.common.js
Labels: спринт2

#68 #46 leaderboard api
  package-lock.json
  package.json
  src/api/LeaderboardAPI.ts
  src/components/loginForm/LoginForm.tsx
  src/components/loginForm/types.ts
  src/components/registrationForm/RegistrationForm.tsx
  src/components/registrationForm/types.ts
  src/pages/leaderboard/Leaderboard.tsx
  src/store/reducers/profile.ts
  src/types/models.ts
Labels: API, Спринт3

#71 #69 game interface
  package.json
  src/components/playground/Playground.tsx
  src/engine/KeyboardManager.ts
  src/engine/Levels.ts
  src/engine/PlayerManager.ts
  src/engine/world/Eagle.ts
  src/pages/game/Game.tsx
  src/pages/game/game.scss
  src/pages/game/gameInterface/GameInterface.tsx
  src/pages/game/gameInterface/game-interface.scss
  src/pages/game/gameInterface/types.ts
  tsconfig.json
  webpack/webpack.common.js
Labels: bug, engine, invalid

#72 Рефакторинг redux-файлов, приведение к единому виду.
  src/engine/CollisionManager.ts
  src/pages/forum/Forum.tsx
  src/pages/forumThread/ForumThread.tsx
  src/pages/profileEdit/ProfileEdit.tsx
  src/store/actions/auth.ts
  src/store/actions/forum.ts
  src/store/actions/profile.ts
  src/store/actionsCreators/auth.ts
  src/store/actionsCreators/forum.ts
  src/store/actionsCreators/profile.ts
  src/store/reducers/auth.ts
  src/store/reducers/forum.ts
  src/store/reducers/profile.ts
  src/store/store.ts
  src/store/types.ts
  src/utils/responseHandle.ts
Labels: API, refactoring
