Repository shchegol/reactive-battle, pull requests merged in 2021-02, with the labels that each got.

#78 #62 fire
  src/engine/AIManager.ts
  src/engine/CollisionManager.ts
  src/engine/EngineBus.ts
  src/engine/KeyboardManager.ts
  src/engine/LevelGenerator.ts
  src/engine/Player.ts
  src/engine/PlayerManager.ts
  src/engine/Scene.ts
  src/engine/SpritesManager.ts
  src/engine/SpritesSheet.ts
  src/engine/Stage.ts
  src/engine/Tank.ts
  src/engine/sprites/Bullet.ts
  src/engine/sprites/Player.ts
  src/engine/sprites/Sprite.ts
  src/engine/sprites/Tank.ts
  src/engine/sprites/world/BrickWall.ts
  src/engine/sprites/world/ConcreteWall.ts
  src/engine/sprites/world/Eagle.ts
  src/engine/sprites/world/Ice.ts
  src/engine/sprites/world/Tree.ts
  src/engine/sprites/world/Wall.ts
  src/engine/sprites/world/Water.ts
  src/images/engine/interface/enemy.svg
  src/images/engine/walls/brick.svg
  src/pages/game/interface/interface.scss
  src/pages/game/playground/Playground.tsx
  src/utils/eventBus.ts
Labels: engine

#79 #74 snackbar
  src/components/portal/Portal.tsx
  src/components/portal/types.ts
  src/components/snackbar/Snackbar.tsx
  src/components/snackbar/snackbar.scss
  src/components/snackbar/types.ts
  src/index.html
  src/index.tsx
  src/store/actions/snackbar.ts
  src/store/actionsCreators/snackbar.ts
  src/store/reducers/index.ts
  src/store/reducers/snackbar.ts
  src/store/types.ts
Labels: enhancement

#83 #63 Попадание пули
  src/engine/CollisionManager.ts
  src/engine/Direction.ts
  src/engine/EngineBus.ts
  src/engine/PlayerManager.ts
  src/engine/Scene.ts
  src/engine/SpritesSheet.ts
  src/engine/sprites/Bullet.ts
  src/engine/sprites/Player.ts
  src/engine/sprites/Tank.ts
  src/engine/sprites/world/BrickWall.ts
  src/engine/sprites/world/Eagle.ts
  src/images/sprite-base.png
Labels: engine

#84 #60 typescript types refactoring
  .eslintrc.json
  src/api/AuthAPI.ts
  src/api/LeaderboardAPI.ts
  src/api/UserAPI.ts
  src/api/types.ts
  src/components/app/App.tsx
  src/pages/forumThread/ForumThread.tsx
  src/pages/game/Game.tsx
  src/pages/profile/Profile.tsx
  src/pages/profileEdit/ProfileEdit.tsx
  src/pages/profileEdit/profileEditForm/ProfileEditForm.tsx
  src/pages/profileEdit/profileEditForm/types.ts
  src/pages/signin/SignIn.tsx
  src/pages/signin/signInForm/types.ts
  src/pages/signup/SignUp.tsx
  src/pages/signup/signUpForm/types.ts
  src/store/actions/auth.ts
  src/store/actions/forum.ts
  src/store/actions/profile.ts
  src/store/actions/snackbar.ts
  src/store/actions/types.ts
  src/store/actions/user.ts
  src/store/actionsCreators/auth.ts
  src/store/actionsCreators/forum.ts
  src/store/actionsCreators/profile.ts
  src/store/actionsCreators/snackbar.ts
  src/store/actionsCreators/types.ts
  src/store/actionsCreators/user.ts
  src/store/reducers/auth.ts
  src/store/reducers/forum.ts
  src/store/reducers/index.ts
  src/store/reducers/profile.ts
  src/store/reducers/snackbar.ts
  src/store/reducers/user.ts
  src/store/types.ts
  src/types/user.ts
  src/utils/responseHandle.ts
Labels: refactoring

#86 #64 spawn
  src/engine/CollisionManager.ts
  src/engine/EnemiesManager.ts
  src/engine/EngineBus.ts
  src/engine/LevelGenerator.ts
  src/engine/Levels.ts
  src/engine/Scene.ts
  src/engine/Stage.ts
  src/engine/sprites/Tank.ts
  src/engine/sprites/enemies/BasicTank.ts
  src/engine/sprites/enemies/EnemyTank.ts
  src/engine/sprites/enemies/FastTank.ts
  src/pages/game/Game.tsx
  src/pages/game/interface/Interface.tsx
  src/pages/game/interface/interface.scss
  src/pages/game/playground/Playground.tsx
Labels: engine

#85 SSR
  package-lock.json
  package.json
  server.js
  src/components/app/App.tsx
  src/components/icon/Icon.tsx
  src/globals.d.ts
  src/index.tsx
  src/pages/forum/Forum.tsx
  src/pages/leaderboard/Leaderboard.tsx
  src/pages/profile/Profile.tsx
  src/pages/signin/SignIn.tsx
  src/server/index.ts
  src/server/renderer.tsx
  src/server/routes.ts
  src/store/actionsCreators/auth.ts
  src/store/reducers/auth.ts
  src/store/reducers/index.ts
  src/store/store.ts
  src/utils/history.ts
  src/utils/responseHandle.ts
  webpack/webpack.client.dev.js
  webpack/webpack.client.prod.js
  webpack/webpack.common.js
  webpack/webpack.server.js
Labels: Спринт3

#88 #65 ai
  package-lock.json
  src/engine/AIManager.ts
  src/engine/CollisionManager.ts
  src/engine/EnemiesManager.ts
  src/engine/EngineBus.ts
  src/engine/LevelGenerator.ts
  src/engine/Levels.ts
  src/engine/PlayerManager.ts
  src/engine/Scene.ts
  src/engine/SpritesManager.ts
  src/engine/Stage.ts
  src/engine/sprites/Bullet.ts
  src/engine/sprites/Player.ts
  src/engine/sprites/Tank.ts
  src/engine/sprites/enemies/BasicTank.ts
  src/engine/sprites/enemies/EnemyTank.ts
  src/engine/sprites/world/BrickWall.ts
  src/engine/sprites/world/ConcreteWall.ts
  src/engine/sprites/world/Spawn.ts
Labels: engine

#87 #45 oauth
  src/api/AuthAPI.ts
  src/components/app/App.tsx
  src/constants.ts
  src/pages/profileEdit/ProfileEdit.tsx
  src/pages/profileEdit/profileEditForm/ProfileEditForm.tsx
  src/pages/profileEdit/profileEditForm/types.ts
  src/pages/signin/SignIn.tsx
  src/pages/signin/signInForm/SignInForm.tsx
  src/server/index.ts
  src/server/renderer.tsx
  src/store/actions/auth.ts
  src/store/actionsCreators/auth.ts
  src/store/actionsCreators/user.ts
  src/store/reducers/auth.ts
  src/store/types.ts
  src/utils/getUrlParams.ts
  webpack/webpack.client.dev.js
Labels: enhancement, Спринт3

#89 #55 hook auth
  src/api/AuthAPI.ts
  src/components/mainTitle/MainTitle.tsx
  src/hocs/withLoading.tsx
  src/hooks/types.ts
  src/hooks/useAuth.ts
  src/hooks/useSnackbar.ts
  src/index.html
  src/index.tsx
  src/pages/loading/Loading.tsx
  src/pages/loading/index.ts
  src/pages/loading/loading.scss
  src/pages/signin/SignIn.tsx
  src/pages/signin/signInForm/SignInForm.tsx
  src/pages/signup/SignUp.tsx
  src/pages/signup/signUpForm/SignUpForm.tsx
  src/server/renderer.tsx
  src/store/actionsCreators/auth.ts
  src/store/actionsCreators/snackbar.ts
  src/store/reducers/auth.ts
  src/store/reducers/snackbar.ts
  src/store/selectors/auth.ts
  src/store/types.ts
  src/utils/responseHandle.ts
Labels: спринт2

#94 #52 SW
  package-lock.json
  package.json
  src/index.html
  src/service-worker.js
  webpack/webpack.common.js
Labels: спринт2

#93 #42 server auth
  package-lock.json
  package.json
  src/api/AuthAPI.ts
  src/api/LeaderboardAPI.ts
  src/api/UserAPI.ts
  src/components/app/App.tsx
  src/components/privateRoute/PrivateRoute.tsx
  src/constants.ts
  src/globals.d.ts
  src/hooks/types.ts
  src/hooks/useAuth.ts
  src/index.tsx
  src/pages/game/Game.tsx
  src/pages/profileEdit/ProfileEdit.tsx
  src/pages/signin/SignIn.tsx
  src/pages/signup/SignUp.tsx
  src/server/index.ts
  src/server/render-middleware.tsx
  src/server/renderer.tsx
  src/server/routes.ts
  src/server/server.ts
  src/store/actions/types.ts
  src/store/actionsCreators/auth.ts
  src/store/actionsCreators/game.ts
  src/store/actionsCreators/user.ts
  src/store/history.ts
  src/store/reducers/auth.ts
  src/store/store.ts
  src/store/types.ts
  src/utils/apiRequest.ts
  src/utils/responseHandle.ts
  webpack/ssr/client.dev.js
  webpack/ssr/client.prod.js
  webpack/ssr/server.js
  webpack/webpack.client.dev.js
  webpack/webpack.client.prod.js
  webpack/webpack.common.js
Labels: Спринт3

#116 #96 Docker with psql
  .gitignore
  Dockerfile
  docker-compose.yml
  sql/schema.sql
Labels: спринт4

#118 #98 forum api
  package-lock.json
  package.json
  sql/schema.sql
  src/constants.ts
  src/engine/Stage.ts
  src/pages/profile/Profile.tsx
  src/pages/profileEdit/ProfileEdit.tsx
  src/server/database/sequelize.ts
  src/server/index.ts
  src/server/models/comment.ts
  src/server/models/topic.ts
  src/server/routes/commentRouterFactory.ts
  src/server/routes/topicRouterFactory.ts
  src/server/server.ts
  src/utils/apiRequest.ts
  tsconfig.json
Labels: API, server, спринт 4

#122 #115 Leaderboard next step
  src/api/LeaderboardAPI.ts
  src/api/types.ts
  src/components/searchBox/SearchBox.tsx
  src/components/searchBox/types.ts
  src/engine/AIManager.ts
  src/engine/EnemiesManager.ts
  src/engine/GameControl.ts
  src/engine/PlayerManager.ts
  src/engine/Scene.ts
  src/engine/SpritesManager.ts
  src/engine/SpritesSheet.ts
  src/engine/Stage.ts
  src/engine/sprites/Bullet.ts
  src/engine/sprites/Sprite.ts
  src/engine/sprites/Tank.ts
  src/engine/sprites/enemies/BasicTank.ts
  src/engine/sprites/enemies/EnemyTank.ts
  src/engine/sprites/enemies/FastTank.ts
  src/engine/sprites/world/BrickWall.ts
  src/engine/sprites/world/ConcreteWall.ts
  src/engine/sprites/world/Eagle.ts
  src/engine/types/GameStates.ts
  src/pages/game/Game.tsx
  src/pages/game/interface/Interface.tsx
  src/pages/game/playground/Playground.tsx
  src/pages/leaderboard/Leaderboard.tsx
  src/pages/leaderboard/playersList/PlayersList.tsx
  src/pages/leaderboard/playersList/index.ts
  src/pages/leaderboard/playersList/playersList.scss
  src/pages/leaderboard/playersList/types.ts
  src/pages/leaderboard/playersListItem/PlayersListItem.tsx
  src/pages/leaderboard/playersListItem/index.ts
  src/pages/leaderboard/playersListItem/playersListItem.scss
  src/pages/leaderboard/playersListItem/types.ts
  src/pages/leaderboard/playersTable/PlayersTable.tsx
  src/pages/leaderboard/playersTable/index.ts
  src/pages/leaderboard/playersTableItem/index.ts
  src/store/actions/game.ts
  src/store/actions/types.ts
  src/store/actionsCreators/game.ts
  src/store/reducers/game.ts
  src/store/types.ts
  src/utils/eventBus.ts
Labels: client, help wanted, спринт 3, спринт 4

#121 #120 change theme client
  src/components/app/App.tsx
  src/components/app/app.scss
  src/components/avatar/Avatar.tsx
  src/components/avatar/avatar.scss
  src/components/avatar/types.ts
  src/components/button/Button.tsx
  src/components/button/button.scss
  src/components/input/input.scss
  src/components/mainTitle/MainTitle.tsx
  src/components/mainTitle/mainTitle.scss
  src/components/snackbar/snackbar.scss
  src/contexts/reply/ReplyContext.tsx
  src/contexts/reply/index.ts
  src/contexts/reply/types.ts
  src/contexts/theme/ThemeContext.tsx
  src/contexts/theme/index.ts
  src/contexts/theme/types.ts
  src/index.tsx
  src/pages/error404/error404.scss
  src/pages/error5xx/error5xx.scss
  src/pages/forum/Forum.tsx
  src/pages/forum/topicItem/topicItem.scss
  src/pages/forumTopic/ForumTopic.tsx
  src/pages/forumTopic/commentItem/CommentItem.tsx
  src/pages/forumTopic/reply/Reply.tsx
  src/pages/forumTopic/reply/reply.scss
  src/pages/game/Game.tsx
  src/pages/game/interface/interface.scss
  src/pages/leaderboard/Leaderboard.tsx
  src/pages/leaderboard/playersListItem/playersListItem.scss
  src/pages/profile/Profile.tsx
  src/pages/profileEdit/ProfileEdit.tsx
  src/pages/profileEdit/profileEditForm/ProfileEditForm.tsx
  src/pages/signin/SignIn.tsx
  src/pages/signup/SignUp.tsx
  src/store/selectors/user.ts
  src/store/types.ts
  src/styles/common/_base.scss
  src/styles/common/_modificators.scss
  src/styles/index.scss
  src/styles/utilities/_themes.scss
  src/styles/utilities/_variables.scss
Labels: client, enhancement, refactoring, спринт 4

#123 #98 forum api
  src/api/AuthAPI.ts
  src/api/ForumAPI.ts
  src/api/UserAPI.ts
  src/pages/forum/Forum.tsx
  src/pages/forum/newTopic/NewTopic.tsx
  src/pages/forumTopic/ForumTopic.tsx
  src/pages/forumTopic/commentItem/CommentItem.tsx
  src/pages/forumTopic/commentItem/types.ts
  src/pages/forumTopic/comments/Comments.tsx
  src/pages/forumTopic/comments/types.ts
  src/pages/forumTopic/reply/Reply.tsx
  src/server/database/sequelize.ts
  src/server/models/comment.ts
  src/server/routes/topicRouterFactory.ts
  src/store/actions/forum.ts
  src/store/actions/types.ts
  src/store/actionsCreators/forum.ts
  src/store/reducers/forum.ts
  src/store/selectors/login.ts
  src/store/types.ts
  src/utils/apiRequest.ts
  src/utils/yandexApiRequest.ts
Labels: API, client, спринт 4
